name: Build and Push Docker Image

# Ejecuta este workflow cuando haya un commit en la rama `main`
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for building multi-platform images (opcional pero recomendado)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Agrega tu usuario de Docker Hub en los secretos de GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Agrega tu contraseña o token en los secretos de GitHub

      # Build the Docker image
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }}
