version: '3'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: todo_db
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
    ports:
      - '3306:3306'
