name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # O "main" si tu rama principal es main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Logear en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Añadir en GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Añadir en GitHub Secrets

      # Construir y empujar la imagen a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./todo-api  # Contexto de construcción, apunta a la carpeta todo-api
          file: ./todo-api/Dockerfile  # Ruta al Dockerfile dentro de todo-api
          push: true
          tags: tu-usuario/nombre-de-la-imagen:latest  # Reemplaza con tu nombre de usuario e imagen

      # Opcional: Etiquetar la imagen con el hash de commit
      - name: Tag image with commit SHA
        run: |
          docker tag tu-usuario/nombre-de-la-imagen:latest tu-usuario/nombre-de-la-imagen:${{ github.sha }}
          docker push tu-usuario/nombre-de-la-imagen:${{ github.sha }}
